name: Lint CI

on:
  push:
    branches: "**"

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: npm ci --ignore-scripts

      - name: Check prettier
        run: npx prettier --check .
